SELECT CLIENT_ACCOUNT_NUMBER, CLIENT_ID, ACCOUNT_TYPE_CODE, CURRENCY_CODE, DISPLAY_BALANCE FROM CLIENT_ACCOUNT WHERE CLIENT_ACCOUNT_NUMBER='1053664521'



-- 4.2.1 Transactional
    SELECT a.CLIENT_ACCOUNT_NUMBER AS ACCOUNT_NUMBER, t.DESCRIPTION AS ACCOUNT_TYPE, a.DISPLAY_BALANCE AS ACCOUNT_BALANCE
    FROM CLIENT_ACCOUNT a
    JOIN ACCOUNT_TYPE t ON t.ACCOUNT_TYPE_CODE= a.ACCOUNT_TYPE_CODE
    WHERE a.ACCOUNT_TYPE_CODE IN ('CHQ', 'SVGS', 'CCRD')
    AND a.CLIENT_ID = 1
    ORDER BY a.DISPLAY_BALANCE DESC

-- 4.2.2 Currency
SELECT a.CLIENT_ACCOUNT_NUMBER, a.CURRENCY_CODE, DISPLAY_BALANCE, r.RATE,
CASE CONVERSION_INDICATOR 
WHEN '/' THEN a.DISPLAY_BALANCE / r.RATE
ELSE a.DISPLAY_BALANCE * r.RATE END RAND_BALANCE
FROM CLIENT c 
JOIN CLIENT_ACCOUNT a ON a.CLIENT_ID = c.CLIENT_ID
JOIN CURRENCY_CONVERSION_RATE r ON r.CURRENCY_CODE = a.CURRENCY_CODE
WHERE ACCOUNT_TYPE_CODE IN ('CFCA')
AND a.CLIENT_ID = 1
ORDER BY RAND_BALANCE DESC;

-- 4.2.3 Withdrawal
TransAcc
+BAL 'SVGS', 'CCRD'

-BAL CHQ MAX(R10Th)

“Insufficient funds”
“Amount not available, would you like to draw X”
“ATM not registered or unfunded”

        SELECT t.ACCOUNT_TYPE_CODE AS ACCOUNT_TYPE_CODE, a.DISPLAY_BALANCE AS ACCOUNT_BALANCE
        FROM CLIENT_ACCOUNT a
        JOIN ACCOUNT_TYPE t ON t.ACCOUNT_TYPE_CODE = a.ACCOUNT_TYPE_CODE
        WHERE t.TRANSACTIONAL = 1
        AND a.CLIENT_ACCOUNT_NUMBER = 4027669028

      SELECT ATM_ID, SUM(TOTAL) AS ATM_BALANCE
      FROM
      (SELECT
      a.ATM_ID, d.VALUE, aa.COUNT, d.VALUE * aa.COUNT AS TOTAL
      FROM ATM_ALLOCATION aa
      JOIN ATM a ON a.ATM_ID = aa.ATM_ID
      JOIN DENOMINATION d  ON d.DENOMINATION_ID = aa.DENOMINATION_ID
      JOIN DENOMINATION_TYPE dt ON dt.DENOMINATION_TYPE_CODE = d.DENOMINATION_TYPE_CODE
      WHERE a.ATM_ID = 1)
      GROUP BY ATM_ID

SELECT NUM_NOTES, VALUE AS DENOMINATION

SELECT * FROM ATM_ALLOCATION

SELECT * FROM ATM

SELECT * FROM DENOMINATION_TYPE

SELECT * FROM DENOMINATION



-- Report1
SELECT c.CLIENT_ID, c.SURNAME, a.CLIENT_ACCOUNT_NUMBER, t.DESCRIPTION, a.DISPLAY_BALANCE
FROM CLIENT c
JOIN CLIENT_ACCOUNT a ON a.CLIENT_ID = c.CLIENT_ID
JOIN ACCOUNT_TYPE t ON t.ACCOUNT_TYPE_CODE = a.ACCOUNT_TYPE_CODE
JOIN (
SELECT c1.CLIENT_ID, MAX(a1.DISPLAY_BALANCE) AS DISPLAY_BALANCE
FROM CLIENT c1
JOIN CLIENT_ACCOUNT a1 ON a1.CLIENT_ID = c1.CLIENT_ID
WHERE a1.ACCOUNT_TYPE_CODE IN ('CCRD', 'CHQ', 'SVGS')
GROUP BY c1.CLIENT_ID
) m ON m.CLIENT_ID = c.CLIENT_ID AND m.DISPLAY_BALANCE = a.DISPLAY_BALANCE
GROUP BY c.CLIENT_ID, c.SURNAME, a.CLIENT_ACCOUNT_NUMBER, t.DESCRIPTION, a.DISPLAY_BALANCE

-- Report2
SELECT c.TITLE, c.NAME, c.SURNAME, t.TRANSACTIONAL_BALANCE, l.LOAN_BALANCE, (n.CURRENCY_BALANCE_ZAR + t.TRANSACTIONAL_BALANCE + l.LOAN_BALANCE) AS NET_POSITION
FROM CLIENT c

    JOIN (
    SELECT c1.CLIENT_ID, AVG(a1.DISPLAY_BALANCE) AS TRANSACTIONAL_BALANCE
    FROM CLIENT c1
    JOIN CLIENT_ACCOUNT a1 ON a1.CLIENT_ID = c1.CLIENT_ID
    WHERE a1.ACCOUNT_TYPE_CODE IN ('CCRD', 'CHQ', 'SVGS')
    --AND c1.CLIENT_ID = 1
    GROUP BY c1.CLIENT_ID
    ) t ON t.CLIENT_ID = c.CLIENT_ID

    JOIN (
    SELECT c1.CLIENT_ID, AVG(a1.DISPLAY_BALANCE) AS LOAN_BALANCE
    FROM CLIENT c1
    JOIN CLIENT_ACCOUNT a1 ON a1.CLIENT_ID = c1.CLIENT_ID
    WHERE a1.ACCOUNT_TYPE_CODE IN ('HLOAN', 'PLOAN')
    --AND c1.CLIENT_ID = 1
    GROUP BY c1.CLIENT_ID
    ) l ON l.CLIENT_ID = c.CLIENT_ID

    JOIN (
    SELECT CLIENT_ID, SUM(ZAR_AMOUNT) AS CURRENCY_BALANCE_ZAR
    FROM
    (SELECT c.CLIENT_ID,
    CASE CONVERSION_INDICATOR
    WHEN '/' THEN a.DISPLAY_BALANCE / r.RATE
    ELSE a.DISPLAY_BALANCE * r.RATE END ZAR_AMOUNT
    FROM CLIENT c
    JOIN CLIENT_ACCOUNT a ON a.CLIENT_ID = c.CLIENT_ID
    JOIN CURRENCY_CONVERSION_RATE r ON r.CURRENCY_CODE = a.CURRENCY_CODE
    WHERE ACCOUNT_TYPE_CODE IN ('CFCA')
    GROUP BY c.CLIENT_ID, CONVERSION_INDICATOR, a.DISPLAY_BALANCE)
    GROUP BY CLIENT_ID
    ) n ON n.CLIENT_ID = c.CLIENT_ID
